# Jekyll configuration

name: "「南」飞岩的博客"
description: Software Developer

url: https://qivmvip.github.io

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ""

social:
  github: qivmvip
  stackoverflow:
  linkedin:
  codepen:
  instagram:
  lastfm:
  rss: feed.xml

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: true

collections:
  tips:
    output: true

# # Google Analytics key, leave blank to ignore
# google_analytics_key:
# # Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
# yandex_metrika: true

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
# disqus: qivmvip
# comments: true

permalink: /:year/:month/:title/
plugins: [jekyll-paginate]
paginate: 10

#highlighter: rouge
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE', vendor]

default_locale: 'zh-rCN'
excerpt_separator: <!--__jekyll_more_separator__-->
